### Register
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
  "name": "Full Name",
  "email": "test@test.com",
  "password": "password"
}

### Login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "password"
}

### Create Event
POST http://localhost:3000/v1/event
Content-Type: application/json

{
  "title": "Title",
  "description": "Description",
  "type": "test",
  "scheduledDateTime": "1691126943422",
  "quantity": 1,
  "productPrice": 100,
  "salePrice": 80
}

### Get Event
GET http://localhost:3000/v1/event/64cc8da34b1e68669b27a76c
Content-Type: application/json

### Update Event
PUT http://localhost:3000/v1/event/64cc8da34b1e68669b27a76c
Content-Type: application/json

{
  "title": "Title1",
  "description": "Description1",
  "type": "test",
  "scheduledDateTime": "1691126943422",
  "quantity": 1,
  "productPrice": 100,
  "salePrice": 80
}

### Delete Event
DELETE http://localhost:3000/v1/event/64cc8da34b1e68669b27a76c
