### Register
POST http://localhost:{{port}}/v1/auth/register
Content-Type: application/json

{
  "name": "Full Name",
  "email": "test3@test.com",
  "password": "password"
}

### Login
POST http://localhost:{{port}}/v1/auth/login
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "password"
}

### Create Event
POST http://localhost:{{port}}/v1/event
Content-Type: application/json

{
  "title": "test",
  "description": "test",
  "scheduledDate": "2023-08-19",
  "scheduledTime": "12:03",
  "price": "112"
}

### Get Event List
GET http://localhost:{{port}}/v1/event
Content-Type: application/json

### Get Event
GET http://localhost:{{port}}/v1/event/64cc8da34b1e68669b27a76c
Content-Type: application/json

### Update Event
PUT http://localhost:{{port}}/v1/event/64d43a07787e780c67c1af12
Content-Type: application/json

{
  "title": "test",
  "description": "test",
  "scheduledDate": "2023-08-19",
  "scheduledTime": "12:03",
  "price": "112"
}

### Delete Event
DELETE http://localhost:{{port}}/v1/event/64d996df1c731af833bcb827

### Get Meeting Token
GET http://localhost:{{port}}/v1/meeting/token

### Create Room
POST http://localhost:{{port}}/v1/meeting
Content-Type: application/json

{}

### Validate Room
GET http://localhost:{{port}}/v1/meeting/auqv-uhxc-0suu